INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (4, 2, 1, 1,'descricao 2', '3000', 1, '2022-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (5, 2, 3, 1,'descricao 2', '4000', 1, '2022-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (6, 2, 1, 1,'descricao 2', '5000', 1, '2022-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (7, 2, 3, 1,'descricao 2', '3000', 1, '2022-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (1, 2, 3, 1,'descricao 2', '3000', 1, '2021-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (8, 2, 1, 1,'descricao 2', '3000', 1, '2021-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (10, 2, 3, 1,'descricao 2', '3000', 1, '2021-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (5, 2, 2, 1,'descricao 2', '3000', 1, '2021-01-01');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (4, 2, 3, 4,'NOVA ORDEM DE SERVIÇO', '6000', 1, '2022-03-16');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (5, 2, 3, 4,'NOVA ORDEM DE SERVIÇO', '7000', 1, '2022-03-16');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (6, 2, 3, 3,'NOVA ORDEM DE SERVIÇO', '8000', 1, '2022-03-16');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (7, 2, 3, 5,'NOVA ORDEM DE SERVIÇO', '10000', 1, '2022-03-16');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (1, 2, 3, 4,'NOVA ORDEM DE SERVIÇO', '88000', 1, '2021-03-20');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (8, 2, 1, 5,'NOVA ORDEM DE SERVIÇO', '22000', 1, '2021-03-18');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (10, 2, 1, 4,'NOVA ORDEM DE SERVIÇO', '44000', 1, '2021-03-19');
INSERT INTO ordem_servico (cliente_id, produto_id, autor_id, status_id, descricao, valor_total, responsavel_id, criado_em) values (5, 2, 1, 3,'NOVA ORDEM DE SERVIÇO', '9000', 1, '2021-03-16');
